name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas

      - name: Fetch Google Sheets data
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python <<EOF
          import os
          import json
          from google.oauth2.service_account import Credentials
          from googleapiclient.discovery import build
          import pandas as pd

          # Kimlik bilgilerini ayarla
          creds_json = os.environ['GOOGLE_SHEETS_CREDENTIALS']
          creds_dict = json.loads(creds_json)
          creds = Credentials.from_service_account_info(creds_dict)

          # Sheets API'sini başlat
          service = build('sheets', 'v4', credentials=creds)

          # Verileri çek
          sheet = service.spreadsheets()
          result = sheet.values().get(spreadsheetId=os.environ['SPREADSHEET_ID'],
                                      range='FormResponses!A:AX').execute()
          values = result.get('values', [])

          # Verileri DataFrame'e dönüştür
          df = pd.DataFrame(values[1:], columns=values[0])

          # CSV olarak kaydet
          df.to_csv('google_sheets_data.csv', index=False)
          print("Veriler başarıyla çekildi ve kaydedildi.")
          EOF

      - name: Debug Spreadsheet Info
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python <<EOF
          import os
          import json
          from google.oauth2.service_account import Credentials
          from googleapiclient.discovery import build

          creds_json = os.environ['GOOGLE_SHEETS_CREDENTIALS']
          creds_dict = json.loads(creds_json)
          creds = Credentials.from_service_account_info(creds_dict)

          service = build('sheets', 'v4', credentials=creds)
          sheet = service.spreadsheets()
          
          metadata = sheet.get(spreadsheetId=os.environ['SPREADSHEET_ID']).execute()
          print("Spreadsheet başlığı:", metadata['properties']['title'])
          print("Sayfa isimleri:", [sheet['properties']['title'] for sheet in metadata['sheets']])
          EOF

      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "hersoy09@@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add google_sheets_data.csv
          git commit -m "Update data from Google Sheets" || exit 0
          git push
          git push https://${GITHUB_TOKEN}@github.com/HErsoy09/isg.git

